services:
  - type: worker
    name: pubg-uc-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: BOT_USERNAME
        sync: false
    disk:
      name: bot-data
      mountPath: /app/data
      sizeGB: 1
